config/routes.rb
Rails.application.routes.draw do
  root to: 'root#root'
  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]

  namespace :api, defaults: { format: :json } do
    resources :listings
    resources :reviews
    resources :reservations
    resources :users
  end

end

app/views/shared/_messages.html.erb
<% [:errors, :warnings].each do |type| %>
  <% if flash[type] %>
  <ul>
    <% flash[type].each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/#">last<span>airbnb</span></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <div id="search">
        <form class="navbar-form navbar-left" role="search">
          <div class="search-input-wrap form-group">
            <input type="text" class="form-control" placeholder="Where are you going?">
          </div>
        </form>
      </div>

      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <!-- <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.name %><span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </li> -->
          <li>
            <a><%= current_user.name %></a>
          </li>
          <li><%= link_to 'Log Out', session_url(session[:token]), method: :delete %></li>
        <% else %>
          <li><%= link_to 'Log in', new_session_url, id: 'login' %></li>
          <li><%= link_to 'Sign up', new_user_url, id: 'signup' %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>